<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TO DO LIST - Task List</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body style="background-color: #bbbbf5;">

<main class="container mx-auto mt-10 lg:mt-20">
    <div class="max-w-full mx-auto">
        <div class="bg-white shadow-md rounded-3xl px-8 pt-6 pb-8 mb-4">
            <h1 class="text-center text-2xl font-bold mb-4" style="color: #141439;">TO DO LIST <br> Task List</h1>
            <div class="mb-6">
                <table class="min-w-full">
                    <thead>
                        <tr>
                            <th class="px-4 py-2">Id</th>
                            <th class="px-4 py-2">Task</th>
                            <th class="px-4 py-2">Status</th>
                            <th class="px-4 py-2">Starts at</th>
                            <th class="px-4 py-2">Deadline</th>
                            <th class="px-4 py-2">Created by</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!-- Boton para volver al index -->
            <div class="mb-6 text-center">
                <a href="index.php" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" style="background-color: #141439;">Back to Home</a>
            </div>
            <div class="text-muted text-center mt-4 text-xs" style="color: #141439;">Thank you for using this app created by Gonzalo and Diega.</div>
        </div>
    </div>
</main>

</body>
</html>